const countryDialData = [
  {
    countryCode: "US",
    dialCode: "+1",
    name: "United States",
    flag: "https://flagcdn.com/us.svg",
  },
  {
    countryCode: "CA",
    dialCode: "+1",
    name: "Canada",
    flag: "https://flagcdn.com/ca.svg",
  },
  {
    countryCode: "AF",
    dialCode: "+93",
    name: "Afghanistan",
    flag: "https://flagcdn.com/af.svg",
  },
  {
    countryCode: "AL",
    dialCode: "+355",
    name: "Albania",
    flag: "https://flagcdn.com/al.svg",
  },
  {
    countryCode: "DZ",
    dialCode: "+213",
    name: "Algeria",
    flag: "https://flagcdn.com/dz.svg",
  },
  {
    countryCode: "AS",
    dialCode: "+1684",
    name: "American Samoa",
    flag: "https://flagcdn.com/as.svg",
  },
  {
    countryCode: "AD",
    dialCode: "+376",
    name: "Andorra",
    flag: "https://flagcdn.com/ad.svg",
  },
  {
    countryCode: "AO",
    dialCode: "+244",
    name: "Angola",
    flag: "https://flagcdn.com/ao.svg",
  },
  {
    countryCode: "AI",
    dialCode: "+1264",
    name: "Anguilla",
    flag: "https://flagcdn.com/ai.svg",
  },
  {
    countryCode: "AQ",
    dialCode: "+672",
    name: "Antarctica",
    flag: "https://flagcdn.com/aq.svg",
  },
  {
    countryCode: "AR",
    dialCode: "+54",
    name: "Argentina",
    flag: "https://flagcdn.com/ar.svg",
  },
  {
    countryCode: "AM",
    dialCode: "+374",
    name: "Armenia",
    flag: "https://flagcdn.com/am.svg",
  },
  {
    countryCode: "AW",
    dialCode: "+297",
    name: "Aruba",
    flag: "https://flagcdn.com/aw.svg",
  },
  {
    countryCode: "AU",
    dialCode: "+61",
    name: "Australia",
    flag: "https://flagcdn.com/au.svg",
  },
  {
    countryCode: "AT",
    dialCode: "+43",
    name: "Austria",
    flag: "https://flagcdn.com/at.svg",
  },
  {
    countryCode: "AZ",
    dialCode: "+994",
    name: "Azerbaijan",
    flag: "https://flagcdn.com/az.svg",
  },
  {
    countryCode: "BS",
    dialCode: "+1242",
    name: "Bahamas",
    flag: "https://flagcdn.com/bs.svg",
  },
  {
    countryCode: "BH",
    dialCode: "+973",
    name: "Bahrain",
    flag: "https://flagcdn.com/bh.svg",
  },
  {
    countryCode: "BD",
    dialCode: "+880",
    name: "Bangladesh",
    flag: "https://flagcdn.com/bd.svg",
  },
  {
    countryCode: "BB",
    dialCode: "+1246",
    name: "Barbados",
    flag: "https://flagcdn.com/bb.svg",
  },
  {
    countryCode: "BY",
    dialCode: "+375",
    name: "Belarus",
    flag: "https://flagcdn.com/by.svg",
  },
  {
    countryCode: "BE",
    dialCode: "+32",
    name: "Belgium",
    flag: "https://flagcdn.com/be.svg",
  },
  {
    countryCode: "BZ",
    dialCode: "+501",
    name: "Belize",
    flag: "https://flagcdn.com/bz.svg",
  },
  {
    countryCode: "BJ",
    dialCode: "+229",
    name: "Benin",
    flag: "https://flagcdn.com/bj.svg",
  },
  {
    countryCode: "BT",
    dialCode: "+975",
    name: "Bhutan",
    flag: "https://flagcdn.com/bt.svg",
  },
  {
    countryCode: "BO",
    dialCode: "+591",
    name: "Bolivia",
    flag: "https://flagcdn.com/bo.svg",
  },
  {
    countryCode: "BA",
    dialCode: "+387",
    name: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/ba.svg",
  },
  {
    countryCode: "BW",
    dialCode: "+267",
    name: "Botswana",
    flag: "https://flagcdn.com/bw.svg",
  },
  {
    countryCode: "BR",
    dialCode: "+55",
    name: "Brazil",
    flag: "https://flagcdn.com/br.svg",
  },
  {
    countryCode: "BN",
    dialCode: "+673",
    name: "Brunei Darussalam",
    flag: "https://flagcdn.com/bn.svg",
  },
  {
    countryCode: "BG",
    dialCode: "+359",
    name: "Bulgaria",
    flag: "https://flagcdn.com/bg.svg",
  },
  {
    countryCode: "BF",
    dialCode: "+226",
    name: "Burkina Faso",
    flag: "https://flagcdn.com/bf.svg",
  },
  {
    countryCode: "BI",
    dialCode: "+257",
    name: "Burundi",
    flag: "https://flagcdn.com/bi.svg",
  },
  {
    countryCode: "KH",
    dialCode: "+855",
    name: "Cambodia",
    flag: "https://flagcdn.com/kh.svg",
  },
  {
    countryCode: "CM",
    dialCode: "+237",
    name: "Cameroon",
    flag: "https://flagcdn.com/cm.svg",
  },
  {
    countryCode: "CA",
    dialCode: "+1",
    name: "Canada",
    flag: "https://flagcdn.com/ca.svg",
  },
  {
    countryCode: "CV",
    dialCode: "+238",
    name: "Cape Verde",
    flag: "https://flagcdn.com/cv.svg",
  },
  {
    countryCode: "KY",
    dialCode: "+1345",
    name: "Cayman Islands",
    flag: "https://flagcdn.com/ky.svg",
  },
  {
    countryCode: "CF",
    dialCode: "+236",
    name: "Central African Republic",
    flag: "https://flagcdn.com/cf.svg",
  },
  {
    countryCode: "TD",
    dialCode: "+235",
    name: "Chad",
    flag: "https://flagcdn.com/td.svg",
  },
  {
    countryCode: "CL",
    dialCode: "+56",
    name: "Chile",
    flag: "https://flagcdn.com/cl.svg",
  },
  {
    countryCode: "CN",
    dialCode: "+86",
    name: "China",
    flag: "https://flagcdn.com/cn.svg",
  },
  {
    countryCode: "CO",
    dialCode: "+57",
    name: "Colombia",
    flag: "https://flagcdn.com/co.svg",
  },
  {
    countryCode: "KM",
    dialCode: "+269",
    name: "Comoros",
    flag: "https://flagcdn.com/km.svg",
  },
  {
    countryCode: "CG",
    dialCode: "+242",
    name: "Congo",
    flag: "https://flagcdn.com/cg.svg",
  },
  {
    countryCode: "CD",
    dialCode: "+243",
    name: "Congo, Democratic Republic of the",
    flag: "https://flagcdn.com/cd.svg",
  },
  {
    countryCode: "CK",
    dialCode: "+682",
    name: "Cook Islands",
    flag: "https://flagcdn.com/ck.svg",
  },
  {
    countryCode: "CR",
    dialCode: "+506",
    name: "Costa Rica",
    flag: "https://flagcdn.com/cr.svg",
  },
  {
    countryCode: "CI",
    dialCode: "+225",
    name: "Côte d'Ivoire",
    flag: "https://flagcdn.com/ci.svg",
  },
  {
    countryCode: "HR",
    dialCode: "+385",
    name: "Croatia",
    flag: "https://flagcdn.com/hr.svg",
  },
  {
    countryCode: "CU",
    dialCode: "+53",
    name: "Cuba",
    flag: "https://flagcdn.com/cu.svg",
  },
  {
    countryCode: "CY",
    dialCode: "+357",
    name: "Cyprus",
    flag: "https://flagcdn.com/cy.svg",
  },
  {
    countryCode: "CZ",
    dialCode: "+420",
    name: "Czech Republic",
    flag: "https://flagcdn.com/cz.svg",
  },
  {
    countryCode: "DK",
    dialCode: "+45",
    name: "Denmark",
    flag: "https://flagcdn.com/dk.svg",
  },
  {
    countryCode: "DJ",
    dialCode: "+253",
    name: "Djibouti",
    flag: "https://flagcdn.com/dj.svg",
  },
  {
    countryCode: "DM",
    dialCode: "+1767",
    name: "Dominica",
    flag: "https://flagcdn.com/dm.svg",
  },
  {
    countryCode: "DO",
    dialCode: "+1",
    name: "Dominican Republic",
    flag: "https://flagcdn.com/do.svg",
  },
  {
    countryCode: "EC",
    dialCode: "+593",
    name: "Ecuador",
    flag: "https://flagcdn.com/ec.svg",
  },
  {
    countryCode: "EG",
    dialCode: "+20",
    name: "Egypt",
    flag: "https://flagcdn.com/eg.svg",
  },
  {
    countryCode: "SV",
    dialCode: "+503",
    name: "El Salvador",
    flag: "https://flagcdn.com/sv.svg",
  },
  {
    countryCode: "GQ",
    dialCode: "+240",
    name: "Equatorial Guinea",
    flag: "https://flagcdn.com/gq.svg",
  },
  {
    countryCode: "ER",
    dialCode: "+291",
    name: "Eritrea",
    flag: "https://flagcdn.com/er.svg",
  },
  {
    countryCode: "EE",
    dialCode: "+372",
    name: "Estonia",
    flag: "https://flagcdn.com/ee.svg",
  },
  {
    countryCode: "SZ",
    dialCode: "+268",
    name: "Eswatini",
    flag: "https://flagcdn.com/sz.svg",
  },
  {
    countryCode: "ET",
    dialCode: "+251",
    name: "Ethiopia",
    flag: "https://flagcdn.com/et.svg",
  },
  {
    countryCode: "FK",
    dialCode: "+500",
    name: "Falkland Islands",
    flag: "https://flagcdn.com/fk.svg",
  },
  {
    countryCode: "FO",
    dialCode: "+298",
    name: "Faroe Islands",
    flag: "https://flagcdn.com/fo.svg",
  },
  {
    countryCode: "FJ",
    dialCode: "+679",
    name: "Fiji",
    flag: "https://flagcdn.com/fj.svg",
  },
  {
    countryCode: "FI",
    dialCode: "+358",
    name: "Finland",
    flag: "https://flagcdn.com/fi.svg",
  },
  {
    countryCode: "FR",
    dialCode: "+33",
    name: "France",
    flag: "https://flagcdn.com/fr.svg",
  },
  {
    countryCode: "GF",
    dialCode: "+594",
    name: "French Guiana",
    flag: "https://flagcdn.com/gf.svg",
  },
  {
    countryCode: "PF",
    dialCode: "+689",
    name: "French Polynesia",
    flag: "https://flagcdn.com/pf.svg",
  },
  {
    countryCode: "GA",
    dialCode: "+241",
    name: "Gabon",
    flag: "https://flagcdn.com/ga.svg",
  },
  {
    countryCode: "GM",
    dialCode: "+220",
    name: "Gambia",
    flag: "https://flagcdn.com/gm.svg",
  },
  {
    countryCode: "GE",
    dialCode: "+995",
    name: "Georgia",
    flag: "https://flagcdn.com/ge.svg",
  },
  {
    countryCode: "DE",
    dialCode: "+49",
    name: "Germany",
    flag: "https://flagcdn.com/de.svg",
  },
  {
    countryCode: "GH",
    dialCode: "+233",
    name: "Ghana",
    flag: "https://flagcdn.com/gh.svg",
  },
  {
    countryCode: "GI",
    dialCode: "+350",
    name: "Gibraltar",
    flag: "https://flagcdn.com/gi.svg",
  },
  {
    countryCode: "GR",
    dialCode: "+30",
    name: "Greece",
    flag: "https://flagcdn.com/gr.svg",
  },
  {
    countryCode: "GL",
    dialCode: "+299",
    name: "Greenland",
    flag: "https://flagcdn.com/gl.svg",
  },
  {
    countryCode: "GD",
    dialCode: "+1473",
    name: "Grenada",
    flag: "https://flagcdn.com/gd.svg",
  },
  {
    countryCode: "GP",
    dialCode: "+590",
    name: "Guadeloupe",
    flag: "https://flagcdn.com/gp.svg",
  },
  {
    countryCode: "GU",
    dialCode: "+1671",
    name: "Guam",
    flag: "https://flagcdn.com/gu.svg",
  },
  {
    countryCode: "GT",
    dialCode: "+502",
    name: "Guatemala",
    flag: "https://flagcdn.com/gt.svg",
  },
  {
    countryCode: "GG",
    dialCode: "+44",
    name: "Guernsey",
    flag: "https://flagcdn.com/gg.svg",
  },
  {
    countryCode: "GN",
    dialCode: "+224",
    name: "Guinea",
    flag: "https://flagcdn.com/gn.svg",
  },
  {
    countryCode: "GW",
    dialCode: "+245",
    name: "Guinea-Bissau",
    flag: "https://flagcdn.com/gw.svg",
  },
  {
    countryCode: "GY",
    dialCode: "+592",
    name: "Guyana",
    flag: "https://flagcdn.com/gy.svg",
  },
  {
    countryCode: "HT",
    dialCode: "+509",
    name: "Haiti",
    flag: "https://flagcdn.com/ht.svg",
  },
  {
    countryCode: "HM",
    dialCode: "+672",
    name: "Heard Island and McDonald Islands",
    flag: "https://flagcdn.com/hm.svg",
  },
  {
    countryCode: "HN",
    dialCode: "+504",
    name: "Honduras",
    flag: "https://flagcdn.com/hn.svg",
  },
  {
    countryCode: "HK",
    dialCode: "+852",
    name: "Hong Kong",
    flag: "https://flagcdn.com/hk.svg",
  },
  {
    countryCode: "HU",
    dialCode: "+36",
    name: "Hungary",
    flag: "https://flagcdn.com/hu.svg",
  },
  {
    countryCode: "IS",
    dialCode: "+354",
    name: "Iceland",
    flag: "https://flagcdn.com/is.svg",
  },
  {
    countryCode: "IN",
    dialCode: "+91",
    name: "India",
    flag: "https://flagcdn.com/in.svg",
  },
  {
    countryCode: "ID",
    dialCode: "+62",
    name: "Indonesia",
    flag: "https://flagcdn.com/id.svg",
  },
  {
    countryCode: "IR",
    dialCode: "+98",
    name: "Iran",
    flag: "https://flagcdn.com/ir.svg",
  },
  {
    countryCode: "IQ",
    dialCode: "+964",
    name: "Iraq",
    flag: "https://flagcdn.com/iq.svg",
  },
  {
    countryCode: "IE",
    dialCode: "+353",
    name: "Ireland",
    flag: "https://flagcdn.com/ie.svg",
  },
  {
    countryCode: "IL",
    dialCode: "+972",
    name: "Israel",
    flag: "https://flagcdn.com/il.svg",
  },
  {
    countryCode: "IT",
    dialCode: "+39",
    name: "Italy",
    flag: "https://flagcdn.com/it.svg",
  },
  {
    countryCode: "JM",
    dialCode: "+1",
    name: "Jamaica",
    flag: "https://flagcdn.com/jm.svg",
  },
  {
    countryCode: "JP",
    dialCode: "+81",
    name: "Japan",
    flag: "https://flagcdn.com/jp.svg",
  },
  {
    countryCode: "JE",
    dialCode: "+44",
    name: "Jersey",
    flag: "https://flagcdn.com/je.svg",
  },
  {
    countryCode: "JO",
    dialCode: "+962",
    name: "Jordan",
    flag: "https://flagcdn.com/jo.svg",
  },
  {
    countryCode: "KZ",
    dialCode: "+7",
    name: "Kazakhstan",
    flag: "https://flagcdn.com/kz.svg",
  },
  {
    countryCode: "KE",
    dialCode: "+254",
    name: "Kenya",
    flag: "https://flagcdn.com/ke.svg",
  },
  {
    countryCode: "KI",
    dialCode: "+686",
    name: "Kiribati",
    flag: "https://flagcdn.com/ki.svg",
  },
  {
    countryCode: "KW",
    dialCode: "+965",
    name: "Kuwait",
    flag: "https://flagcdn.com/kw.svg",
  },
  {
    countryCode: "KG",
    dialCode: "+996",
    name: "Kyrgyzstan",
    flag: "https://flagcdn.com/kg.svg",
  },
  {
    countryCode: "LA",
    dialCode: "+856",
    name: "Laos",
    flag: "https://flagcdn.com/la.svg",
  },
  {
    countryCode: "LV",
    dialCode: "+371",
    name: "Latvia",
    flag: "https://flagcdn.com/lv.svg",
  },
  {
    countryCode: "LB",
    dialCode: "+961",
    name: "Lebanon",
    flag: "https://flagcdn.com/lb.svg",
  },
  {
    countryCode: "LS",
    dialCode: "+266",
    name: "Lesotho",
    flag: "https://flagcdn.com/ls.svg",
  },
  {
    countryCode: "LR",
    dialCode: "+231",
    name: "Liberia",
    flag: "https://flagcdn.com/lr.svg",
  },
  {
    countryCode: "LY",
    dialCode: "+218",
    name: "Libya",
    flag: "https://flagcdn.com/ly.svg",
  },
  {
    countryCode: "LI",
    dialCode: "+423",
    name: "Liechtenstein",
    flag: "https://flagcdn.com/li.svg",
  },
  {
    countryCode: "LT",
    dialCode: "+370",
    name: "Lithuania",
    flag: "https://flagcdn.com/lt.svg",
  },
  {
    countryCode: "LU",
    dialCode: "+352",
    name: "Luxembourg",
    flag: "https://flagcdn.com/lu.svg",
  },
  {
    countryCode: "MO",
    dialCode: "+853",
    name: "Macao",
    flag: "https://flagcdn.com/mo.svg",
  },
  {
    countryCode: "MK",
    dialCode: "+389",
    name: "North Macedonia",
    flag: "https://flagcdn.com/mk.svg",
  },
  {
    countryCode: "MG",
    dialCode: "+261",
    name: "Madagascar",
    flag: "https://flagcdn.com/mg.svg",
  },
  {
    countryCode: "MW",
    dialCode: "+265",
    name: "Malawi",
    flag: "https://flagcdn.com/mw.svg",
  },
  {
    countryCode: "MY",
    dialCode: "+60",
    name: "Malaysia",
    flag: "https://flagcdn.com/my.svg",
  },
  {
    countryCode: "MV",
    dialCode: "+960",
    name: "Maldives",
    flag: "https://flagcdn.com/mv.svg",
  },
  {
    countryCode: "ML",
    dialCode: "+223",
    name: "Mali",
    flag: "https://flagcdn.com/ml.svg",
  },
  {
    countryCode: "MT",
    dialCode: "+356",
    name: "Malta",
    flag: "https://flagcdn.com/mt.svg",
  },
  {
    countryCode: "MH",
    dialCode: "+692",
    name: "Marshall Islands",
    flag: "https://flagcdn.com/mh.svg",
  },
  {
    countryCode: "MQ",
    dialCode: "+596",
    name: "Martinique",
    flag: "https://flagcdn.com/mq.svg",
  },
  {
    countryCode: "MR",
    dialCode: "+222",
    name: "Mauritania",
    flag: "https://flagcdn.com/mr.svg",
  },
  {
    countryCode: "MU",
    dialCode: "+230",
    name: "Mauritius",
    flag: "https://flagcdn.com/mu.svg",
  },
  {
    countryCode: "YT",
    dialCode: "+262",
    name: "Mayotte",
    flag: "https://flagcdn.com/yt.svg",
  },
  {
    countryCode: "MX",
    dialCode: "+52",
    name: "Mexico",
    flag: "https://flagcdn.com/mx.svg",
  },
  {
    countryCode: "FM",
    dialCode: "+691",
    name: "Federated States of Micronesia",
    flag: "https://flagcdn.com/fm.svg",
  },
  {
    countryCode: "MD",
    dialCode: "+373",
    name: "Moldova",
    flag: "https://flagcdn.com/md.svg",
  },
  {
    countryCode: "MC",
    dialCode: "+377",
    name: "Monaco",
    flag: "https://flagcdn.com/mc.svg",
  },
  {
    countryCode: "MN",
    dialCode: "+976",
    name: "Mongolia",
    flag: "https://flagcdn.com/mn.svg",
  },
  {
    countryCode: "ME",
    dialCode: "+382",
    name: "Montenegro",
    flag: "https://flagcdn.com/me.svg",
  },
  {
    countryCode: "MS",
    dialCode: "+1664",
    name: "Montserrat",
    flag: "https://flagcdn.com/ms.svg",
  },
  {
    countryCode: "MA",
    dialCode: "+212",
    name: "Morocco",
    flag: "https://flagcdn.com/ma.svg",
  },
  {
    countryCode: "MZ",
    dialCode: "+258",
    name: "Mozambique",
    flag: "https://flagcdn.com/mz.svg",
  },
  {
    countryCode: "MM",
    dialCode: "+95",
    name: "Myanmar",
    flag: "https://flagcdn.com/mm.svg",
  },
  {
    countryCode: "NA",
    dialCode: "+264",
    name: "Namibia",
    flag: "https://flagcdn.com/na.svg",
  },
  {
    countryCode: "NR",
    dialCode: "+674",
    name: "Nauru",
    flag: "https://flagcdn.com/nr.svg",
  },
  {
    countryCode: "NP",
    dialCode: "+977",
    name: "Nepal",
    flag: "https://flagcdn.com/np.svg",
  },
  {
    countryCode: "NL",
    dialCode: "+31",
    name: "Netherlands",
    flag: "https://flagcdn.com/nl.svg",
  },
  {
    countryCode: "NC",
    dialCode: "+687",
    name: "New Caledonia",
    flag: "https://flagcdn.com/nc.svg",
  },
  {
    countryCode: "NZ",
    dialCode: "+64",
    name: "New Zealand",
    flag: "https://flagcdn.com/nz.svg",
  },
  {
    countryCode: "NI",
    dialCode: "+505",
    name: "Nicaragua",
    flag: "https://flagcdn.com/ni.svg",
  },
  {
    countryCode: "NE",
    dialCode: "+227",
    name: "Niger",
    flag: "https://flagcdn.com/ne.svg",
  },
  {
    countryCode: "NG",
    dialCode: "+234",
    name: "Nigeria",
    flag: "https://flagcdn.com/ng.svg",
  },
  {
    countryCode: "NU",
    dialCode: "+683",
    name: "Niue",
    flag: "https://flagcdn.com/nu.svg",
  },
  {
    countryCode: "NF",
    dialCode: "+672",
    name: "Norfolk Island",
    flag: "https://flagcdn.com/nf.svg",
  },
  {
    countryCode: "MP",
    dialCode: "+1670",
    name: "Northern Mariana Islands",
    flag: "https://flagcdn.com/mp.svg",
  },
  {
    countryCode: "NO",
    dialCode: "+47",
    name: "Norway",
    flag: "https://flagcdn.com/no.svg",
  },
  {
    countryCode: "OM",
    dialCode: "+968",
    name: "Oman",
    flag: "https://flagcdn.com/om.svg",
  },
  {
    countryCode: "PK",
    dialCode: "+92",
    name: "Pakistan",
    flag: "https://flagcdn.com/pk.svg",
  },
  {
    countryCode: "PW",
    dialCode: "+680",
    name: "Palau",
    flag: "https://flagcdn.com/pw.svg",
  },
  {
    countryCode: "PS",
    dialCode: "+970",
    name: "Palestine",
    flag: "https://flagcdn.com/ps.svg",
  },
  {
    countryCode: "PA",
    dialCode: "+507",
    name: "Panama",
    flag: "https://flagcdn.com/pa.svg",
  },
  {
    countryCode: "PG",
    dialCode: "+675",
    name: "Papua New Guinea",
    flag: "https://flagcdn.com/pg.svg",
  },
  {
    countryCode: "PY",
    dialCode: "+595",
    name: "Paraguay",
    flag: "https://flagcdn.com/py.svg",
  },
  {
    countryCode: "PE",
    dialCode: "+51",
    name: "Peru",
    flag: "https://flagcdn.com/pe.svg",
  },
  {
    countryCode: "PH",
    dialCode: "+63",
    name: "Philippines",
    flag: "https://flagcdn.com/ph.svg",
  },
  {
    countryCode: "PL",
    dialCode: "+48",
    name: "Poland",
    flag: "https://flagcdn.com/pl.svg",
  },
  {
    countryCode: "PT",
    dialCode: "+351",
    name: "Portugal",
    flag: "https://flagcdn.com/pt.svg",
  },
  {
    countryCode: "PR",
    dialCode: "+1",
    name: "Puerto Rico",
    flag: "https://flagcdn.com/pr.svg",
  },
  {
    countryCode: "QA",
    dialCode: "+974",
    name: "Qatar",
    flag: "https://flagcdn.com/qa.svg",
  },
  {
    countryCode: "RE",
    dialCode: "+262",
    name: "Réunion",
    flag: "https://flagcdn.com/re.svg",
  },
  {
    countryCode: "RO",
    dialCode: "+40",
    name: "Romania",
    flag: "https://flagcdn.com/ro.svg",
  },
  {
    countryCode: "RU",
    dialCode: "+7",
    name: "Russia",
    flag: "https://flagcdn.com/ru.svg",
  },
  {
    countryCode: "RW",
    dialCode: "+250",
    name: "Rwanda",
    flag: "https://flagcdn.com/rw.svg",
  },
  {
    countryCode: "BL",
    dialCode: "+590",
    name: "Saint Barthélemy",
    flag: "https://flagcdn.com/bl.svg",
  },
  {
    countryCode: "SH",
    dialCode: "+290",
    name: "Saint Helena",
    flag: "https://flagcdn.com/sh.svg",
  },
  {
    countryCode: "KN",
    dialCode: "+1869",
    name: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/kn.svg",
  },
  {
    countryCode: "LC",
    dialCode: "+1758",
    name: "Saint Lucia",
    flag: "https://flagcdn.com/lc.svg",
  },
  {
    countryCode: "MF",
    dialCode: "+590",
    name: "Saint Martin",
    flag: "https://flagcdn.com/mf.svg",
  },
  {
    countryCode: "PM",
    dialCode: "+508",
    name: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/pm.svg",
  },
  {
    countryCode: "VC",
    dialCode: "+1784",
    name: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/vc.svg",
  },
  {
    countryCode: "WS",
    dialCode: "+685",
    name: "Samoa",
    flag: "https://flagcdn.com/ws.svg",
  },
  {
    countryCode: "SM",
    dialCode: "+378",
    name: "San Marino",
    flag: "https://flagcdn.com/sm.svg",
  },
  {
    countryCode: "SA",
    dialCode: "+966",
    name: "Saudi Arabia",
    flag: "https://flagcdn.com/sa.svg",
  },
  {
    countryCode: "SN",
    dialCode: "+221",
    name: "Senegal",
    flag: "https://flagcdn.com/sn.svg",
  },
  {
    countryCode: "RS",
    dialCode: "+381",
    name: "Serbia",
    flag: "https://flagcdn.com/rs.svg",
  },
  {
    countryCode: "SC",
    dialCode: "+248",
    name: "Seychelles",
    flag: "https://flagcdn.com/sc.svg",
  },
  {
    countryCode: "SL",
    dialCode: "+232",
    name: "Sierra Leone",
    flag: "https://flagcdn.com/sl.svg",
  },
  {
    countryCode: "SG",
    dialCode: "+65",
    name: "Singapore",
    flag: "https://flagcdn.com/sg.svg",
  },
  {
    countryCode: "SX",
    dialCode: "+1",
    name: "Sint Maarten",
    flag: "https://flagcdn.com/sx.svg",
  },
  {
    countryCode: "SK",
    dialCode: "+421",
    name: "Slovakia",
    flag: "https://flagcdn.com/sk.svg",
  },
  {
    countryCode: "SI",
    dialCode: "+386",
    name: "Slovenia",
    flag: "https://flagcdn.com/si.svg",
  },
  {
    countryCode: "SB",
    dialCode: "+677",
    name: "Solomon Islands",
    flag: "https://flagcdn.com/sb.svg",
  },
  {
    countryCode: "SO",
    dialCode: "+252",
    name: "Somalia",
    flag: "https://flagcdn.com/so.svg",
  },
  {
    countryCode: "ZA",
    dialCode: "+27",
    name: "South Africa",
    flag: "https://flagcdn.com/za.svg",
  },
  {
    countryCode: "GS",
    dialCode: "+500",
    name: "South Georgia and the South Sandwich Islands",
    flag: "https://flagcdn.com/gs.svg",
  },
  {
    countryCode: "KR",
    dialCode: "+82",
    name: "South Korea",
    flag: "https://flagcdn.com/kr.svg",
  },
  {
    countryCode: "SS",
    dialCode: "+211",
    name: "South Sudan",
    flag: "https://flagcdn.com/ss.svg",
  },
  {
    countryCode: "ES",
    dialCode: "+34",
    name: "Spain",
    flag: "https://flagcdn.com/es.svg",
  },
  {
    countryCode: "LK",
    dialCode: "+94",
    name: "Sri Lanka",
    flag: "https://flagcdn.com/lk.svg",
  },
  {
    countryCode: "SD",
    dialCode: "+249",
    name: "Sudan",
    flag: "https://flagcdn.com/sd.svg",
  },
  {
    countryCode: "SR",
    dialCode: "+597",
    name: "Suriname",
    flag: "https://flagcdn.com/sr.svg",
  },
  {
    countryCode: "SJ",
    dialCode: "+47",
    name: "Svalbard and Jan Mayen",
    flag: "https://flagcdn.com/sj.svg",
  },
  {
    countryCode: "SE",
    dialCode: "+46",
    name: "Sweden",
    flag: "https://flagcdn.com/se.svg",
  },
  {
    countryCode: "CH",
    dialCode: "+41",
    name: "Switzerland",
    flag: "https://flagcdn.com/ch.svg",
  },
  {
    countryCode: "SY",
    dialCode: "+963",
    name: "Syria",
    flag: "https://flagcdn.com/sy.svg",
  },
  {
    countryCode: "TW",
    dialCode: "+886",
    name: "Taiwan",
    flag: "https://flagcdn.com/tw.svg",
  },
  {
    countryCode: "TJ",
    dialCode: "+992",
    name: "Tajikistan",
    flag: "https://flagcdn.com/tj.svg",
  },
  {
    countryCode: "TZ",
    dialCode: "+255",
    name: "Tanzania",
    flag: "https://flagcdn.com/tz.svg",
  },
  {
    countryCode: "TH",
    dialCode: "+66",
    name: "Thailand",
    flag: "https://flagcdn.com/th.svg",
  },
  {
    countryCode: "TL",
    dialCode: "+670",
    name: "Timor-Leste",
    flag: "https://flagcdn.com/tl.svg",
  },
  {
    countryCode: "TG",
    dialCode: "+228",
    name: "Togo",
    flag: "https://flagcdn.com/tg.svg",
  },
  {
    countryCode: "TK",
    dialCode: "+690",
    name: "Tokelau",
    flag: "https://flagcdn.com/tk.svg",
  },
  {
    countryCode: "TO",
    dialCode: "+676",
    name: "Tonga",
    flag: "https://flagcdn.com/to.svg",
  },
  {
    countryCode: "TT",
    dialCode: "+1",
    name: "Trinidad and Tobago",
    flag: "https://flagcdn.com/tt.svg",
  },
  {
    countryCode: "TN",
    dialCode: "+216",
    name: "Tunisia",
    flag: "https://flagcdn.com/tn.svg",
  },
  {
    countryCode: "TR",
    dialCode: "+90",
    name: "Turkey",
    flag: "https://flagcdn.com/tr.svg",
  },
  {
    countryCode: "TM",
    dialCode: "+993",
    name: "Turkmenistan",
    flag: "https://flagcdn.com/tm.svg",
  },
  {
    countryCode: "TC",
    dialCode: "+1",
    name: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/tc.svg",
  },
  {
    countryCode: "TV",
    dialCode: "+688",
    name: "Tuvalu",
    flag: "https://flagcdn.com/tv.svg",
  },
  {
    countryCode: "UG",
    dialCode: "+256",
    name: "Uganda",
    flag: "https://flagcdn.com/ug.svg",
  },
  {
    countryCode: "UA",
    dialCode: "+380",
    name: "Ukraine",
    flag: "https://flagcdn.com/ua.svg",
  },
  {
    countryCode: "AE",
    dialCode: "+971",
    name: "United Arab Emirates",
    flag: "https://flagcdn.com/ae.svg",
  },
  {
    countryCode: "GB",
    dialCode: "+44",
    name: "United Kingdom",
    flag: "https://flagcdn.com/gb.svg",
  },
  {
    countryCode: "US",
    dialCode: "+1",
    name: "United States",
    flag: "https://flagcdn.com/us.svg",
  },
  {
    countryCode: "UY",
    dialCode: "+598",
    name: "Uruguay",
    flag: "https://flagcdn.com/uy.svg",
  },
  {
    countryCode: "UZ",
    dialCode: "+998",
    name: "Uzbekistan",
    flag: "https://flagcdn.com/uz.svg",
  },
  {
    countryCode: "VU",
    dialCode: "+678",
    name: "Vanuatu",
    flag: "https://flagcdn.com/vu.svg",
  },
  {
    countryCode: "VE",
    dialCode: "+58",
    name: "Venezuela",
    flag: "https://flagcdn.com/ve.svg",
  },
  {
    countryCode: "VN",
    dialCode: "+84",
    name: "Vietnam",
    flag: "https://flagcdn.com/vn.svg",
  },
  {
    countryCode: "VG",
    dialCode: "+1",
    name: "British Virgin Islands",
    flag: "https://flagcdn.com/vg.svg",
  },
  {
    countryCode: "VI",
    dialCode: "+1",
    name: "U.S. Virgin Islands",
    flag: "https://flagcdn.com/vi.svg",
  },
  {
    countryCode: "WF",
    dialCode: "+681",
    name: "Wallis and Futuna",
    flag: "https://flagcdn.com/wf.svg",
  },
  {
    countryCode: "EH",
    dialCode: "+212",
    name: "Western Sahara",
    flag: "https://flagcdn.com/eh.svg",
  },
  {
    countryCode: "YE",
    dialCode: "+967",
    name: "Yemen",
    flag: "https://flagcdn.com/ye.svg",
  },
  {
    countryCode: "ZM",
    dialCode: "+260",
    name: "Zambia",
    flag: "https://flagcdn.com/zm.svg",
  },
  {
    countryCode: "ZW",
    dialCode: "+263",
    name: "Zimbabwe",
    flag: "https://flagcdn.com/zw.svg",
  },
];

function getCountryByDialCode(dialCode, name) {
  let country;
  if (dialCode) {
    country = countryDialData.find((c) => c.dialCode === dialCode.trim());
  }
  if (name) {
    country = countryDialData.find((c) => c.name === name.trim());
  }
  console.log();
  

  if (!country) {
    return {
      name: "Unknown Country",
      flag: "https://via.placeholder.com/24?text=?",
    };
  }

  return {
    name: country.name,
    flag: country.flag,
  };
}

export default getCountryByDialCode;
