export function getCouponsCustomData() {
  return {
    SampleHeaders: [
      "Coupon Name",
      "Description",
      "Coupon Code",
      "Discount Type",
      "Discount Value",
      "Status",
      "Start Date",
      "End Date",
      "Applicable Plan",
      "Applicable Users",
      "Max Coupon Usage",
      "Created Date",
      "Updated Date",
    ],

    SampleContent: [
      [
        "HALFOFF1",
        "50% off for the first 100 new users on any plan",
        "50NEWE",
        "percentage",
        50,
        "Active",
        "2025-04-07T12:19:00.000Z",
        "2025-04-30T12:19:00.000Z",
        "All",
        "All Users",
        5,
        "2025-04-07T12:23:21.309Z",
        "2025-04-07T13:37:07.115Z",
      ],
      [
        "WELCOME10",
        "10% off on the first purchase for new users",
        "WELCOME10",
        "percentage",
        10,
        "Active",
        "2025-04-01T00:00:00.000Z",
        "2025-04-30T23:59:59.000Z",
        "All",
        "New Users",
        100,
        "2025-04-01T08:00:00.000Z",
        "2025-04-01T08:30:00.000Z",
      ],
      [
        "FREESHIP",
        "Free shipping on orders above $50",
        "FREESHIP",
        "amount",
        0,
        "Active",
        "2025-04-05T00:00:00.000Z",
        "2025-04-20T23:59:59.000Z",
        "All",
        "All Users",
        500,
        "2025-04-05T10:00:00.000Z",
        "2025-04-05T10:30:00.000Z",
      ],
      [
        "SUMMER20",
        "20% off on summer collection",
        "SUMMER20",
        "percentage",
        20,
        "Upcoming",
        "2025-05-01T00:00:00.000Z",
        "2025-05-31T23:59:59.000Z",
        "All",
        "All Users",
        200,
        "2025-04-10T12:00:00.000Z",
        "2025-04-10T12:30:00.000Z",
      ],
      [
        "BULKBUY",
        "5% off on bulk purchases of 10 or more items",
        "BULKBUY",
        "percentage",
        5,
        "Active",
        "2025-04-01T00:00:00.000Z",
        "2025-06-30T23:59:59.000Z",
        "All",
        "All Users",
        50,
        "2025-04-01T09:00:00.000Z",
        "2025-04-01T09:30:00.000Z",
      ],
      [
        "NEWYEAR50",
        "Flat $50 off on orders above $500",
        "NEWYEAR50",
        "amount",
        50,
        "Expired",
        "2025-01-01T00:00:00.000Z",
        "2025-01-31T23:59:59.000Z",
        "All",
        "All Users",
        100,
        "2025-01-01T10:00:00.000Z",
        "2025-01-01T10:30:00.000Z",
      ],
      [
        "LOYALTY15",
        "15% off for loyal customers",
        "LOYALTY15",
        "percentage",
        15,
        "Active",
        "2025-04-01T00:00:00.000Z",
        "2025-12-31T23:59:59.000Z",
        "All",
        "Returning Users",
        300,
        "2025-04-01T11:00:00.000Z",
        "2025-04-01T11:30:00.000Z",
      ],
      [
        "FLASHSALE",
        "30% off during flash sale",
        "FLASH30",
        "percentage",
        30,
        "Active",
        "2025-04-15T12:00:00.000Z",
        "2025-04-15T18:00:00.000Z",
        "All",
        "All Users",
        1000,
        "2025-04-15T10:00:00.000Z",
        "2025-04-15T10:30:00.000Z",
      ],
      [
        "STUDENT10",
        "10% off for students",
        "STUDENT10",
        "percentage",
        10,
        "Active",
        "2025-04-01T00:00:00.000Z",
        "2025-12-31T23:59:59.000Z",
        "All",
        "Students",
        500,
        "2025-04-01T08:00:00.000Z",
        "2025-04-01T08:30:00.000Z",
      ],
      [
        "FESTIVE25",
        "25% off on festive season",
        "FESTIVE25",
        "percentage",
        25,
        "Upcoming",
        "2025-12-01T00:00:00.000Z",
        "2025-12-31T23:59:59.000Z",
        "All",
        "All Users",
        100,
        "2025-11-01T12:00:00.000Z",
        "2025-11-01T12:30:00.000Z",
      ],
    ],
  };
}

export function getDocumentationCustomData() {
  return {
    SampleHeaders: [
      "Module Name",
      "Title",
      "Link Title",
      "Link",
      "Description",
      "Status",
      "Created At",
      "Updated At"
    ],
    SampleContent: [
      [
        "thoughts",
        "Reporting Guide - Basics",
        "Getting Started",
        "https://www.example.com/video/reporting-basics",
        "Learn how to generate and understand basic reports in the Reporting module.",
        "Published",
        "2025-04-08T10:30:00.000Z",
        "2025-04-08T10:30:00.000Z"
      ],
      [
        "roles",
        "Reporting Guide - Basics",
        "Custom Report Filters",
        "https://www.example.com/video/reporting-filters",
        "Discover how to use filters to customize the data in your reports effectively.",
        "Draft",
        "2025-04-08T10:30:00.000Z",
        "2025-04-08T10:30:00.000Z"
      ],
    ]
  };
}




export function getCompaniesSampleData() {
  return {
    SampleHeaders: [
      "Company Name",
      "Company Logo",
      "Company Size",
      "Country",
      "State",
      "City",
      "Address",
      "Zip Code",
      "VAT Number",
      "Status",
      "Admin Name",
      "Admin Email ID",
      "Phone Code", // Updated to match schema mapping
      "Admin Phone", // Updated to match schema mapping
      "Date Format",
      "Time Format",
      "Time Zone",
    ],
    SampleContent: [
      [
        "NextGen Solutions",
        "https://via.placeholder.com/100",
        "100-300",
        "USA",
        "New York",
        "New York City",
        "500 Wall Street",
        "10005",
        "VAT987654",
        "Active",
        "David Johnson",
        "david.johnson@nextgensol.com",
        "+1",
        "212-555-7890",
        "MM/DD/YYYY",
        "hh:mm A",
        "America/New_York",
      ],
      [
        "CyberNet",
        "https://via.placeholder.com/100",
        "500-800",
        "Canada",
        "British Columbia",
        "Vancouver",
        "250 Cyber Avenue",
        "V5K 0A1",
        "VAT456321",
        "Inactive",
        "Sophia Martinez",
        "sophia.martinez@cybernet.co",
        "+1",
        "604-123-4567",
        "DD-MM-YYYY",
        "HH:mm",
        "America/Vancouver",
      ],
      [
        "GlobalTech",
        "https://via.placeholder.com/100",
        "1000+",
        "UK",
        "Scotland",
        "Edinburgh",
        "75 Royal Mile",
        "EH1 1RF",
        "VAT789654",
        "Pending",
        "James Wilson",
        "james.wilson@globaltech.io",
        "+44",
        "131-555-8888",
        "YYYY-MM-DD",
        "HH:mm:ss",
        "Europe/London",
      ],
      [
        "DataLogic",
        "https://via.placeholder.com/100",
        "50-200",
        "Germany",
        "Hessen",
        "Frankfurt",
        "33 Finance Street",
        "60329",
        "VAT321789",
        "Active",
        "Olivia Brown",
        "olivia.brown@datalogic.ai",
        "+49",
        "69-1234-5678",
        "DD/MM/YYYY",
        "h:mm A",
        "Europe/Berlin",
      ],
      [
        "CloudSphere",
        "https://via.placeholder.com/100",
        "500-1500",
        "Australia",
        "Victoria",
        "Melbourne",
        "88 Cloud Lane",
        "3000",
        "VAT654987",
        "Active",
        "Ethan White",
        "ethan.white@cloudsphere.au",
        "+61",
        "3-5555-6789",
        "YYYY-MM-DD",
        "HH:mm:ss",
        "Australia/Melbourne",
      ],
      [
        "InnovaSoft",
        "https://via.placeholder.com/100",
        "100-300",
        "France",
        "Île-de-France",
        "Paris",
        "22 Rue du Tech",
        "75001",
        "VAT852963",
        "Pending",
        "Emma Dupont",
        "emma.dupont@innovasoft.fr",
        "+33",
        "1-2345-6789",
        "DD-MM-YYYY",
        "HH:mm",
        "Europe/Paris",
      ],
      [
        "AI Hub",
        "https://via.placeholder.com/100",
        "200-500",
        "India",
        "Maharashtra",
        "Mumbai",
        "77 AI Street",
        "400001",
        "VAT147258",
        "Active",
        "Ravi Kumar",
        "ravi.kumar@aihub.in",
        "+91",
        "22-9876-5432",
        "YYYY-MM-DD",
        "hh:mm A",
        "Asia/Kolkata",
      ],
      [
        "CodeFusion",
        "https://via.placeholder.com/100",
        "300-600",
        "Japan",
        "Tokyo",
        "Tokyo",
        "555 Code Lane",
        "100-0001",
        "VAT369852",
        "Inactive",
        "Hiroshi Tanaka",
        "hiroshi.tanaka@codefusion.jp",
        "+81",
        "3-1234-5678",
        "YYYY/MM/DD",
        "HH:mm",
        "Asia/Tokyo",
      ],
      [
        "TechNova",
        "https://via.placeholder.com/100",
        "50-200",
        "Singapore",
        "Singapore",
        "Singapore",
        "18 Tech Park",
        "048619",
        "VAT654123",
        "Pending",
        "Lily Wong",
        "lily.wong@technova.sg",
        "+65",
        "6789-1234",
        "DD/MM/YYYY",
        "h:mm A",
        "Asia/Singapore",
      ],
      [
        "ByteWorks",
        "https://via.placeholder.com/100",
        "500-1000",
        "South Korea",
        "Seoul",
        "Seoul",
        "99 Digital Valley",
        "04567",
        "VAT987321",
        "Active",
        "Min-woo Park",
        "minwoo.park@byteworks.kr",
        "+82",
        "2-5678-1234",
        "YYYY.MM.DD",
        "HH:mm",
        "Asia/Seoul",
      ],
      [
        "SoftEdge",
        "https://via.placeholder.com/100",
        "200-500",
        "Brazil",
        "São Paulo",
        "São Paulo",
        "66 Avenida Paulista",
        "01311-000",
        "VAT321456",
        "Active",
        "Carlos Silva",
        "carlos.silva@softedge.br",
        "+55",
        "11-99876-5432",
        "DD-MM-YYYY",
        "hh:mm A",
        "America/Sao_Paulo",
      ],
      [
        "NeuralNet",
        "https://via.placeholder.com/100",
        "100-300",
        "China",
        "Beijing",
        "Beijing",
        "88 AI Street",
        "100000",
        "VAT654789",
        "Pending",
        "Wei Zhang",
        "wei.zhang@neuralnet.cn",
        "+86",
        "10-6789-1234",
        "YYYY年MM月DD日",
        "HH:mm",
        "Asia/Shanghai",
      ],
      [
        "QuantumSoft",
        "https://via.placeholder.com/100",
        "1000+",
        "UAE",
        "Dubai",
        "Dubai",
        "22 Business Bay",
        "00000",
        "VAT852147",
        "Inactive",
        "Ahmed Al-Farsi",
        "ahmed.alfarsi@quantumsoft.ae",
        "+971",
        "4-9876-5432",
        "YYYY-MM-DD",
        "HH:mm:ss",
        "Asia/Dubai",
      ],
      [
        "NetFlow",
        "https://via.placeholder.com/100",
        "50-100",
        "South Africa",
        "Gauteng",
        "Johannesburg",
        "101 Nelson Mandela Drive",
        "2000",
        "VAT951753",
        "Active",
        "Thabo Mokoena",
        "thabo.mokoena@netflow.za",
        "+27",
        "11-555-6789",
        "DD/MM/YYYY",
        "hh:mm A",
        "Africa/Johannesburg",
      ],
      [
        "CodeBlitz",
        "https://via.placeholder.com/100",
        "100-500",
        "Mexico",
        "CDMX",
        "Mexico City",
        "44 Reforma Avenue",
        "06500",
        "VAT753159",
        "Pending",
        "Luis Hernandez",
        "luis.hernandez@codeblitz.mx",
        "+52",
        "55-9876-5432",
        "YYYY-MM-DD",
        "HH:mm",
        "America/Mexico_City",
      ],
      [
        "InnovateAI",
        "https://via.placeholder.com/100",
        "500-1000",
        "Russia",
        "Moscow",
        "Moscow",
        "77 AI Park",
        "101000",
        "VAT159357",
        "Active",
        "Ivan Petrov",
        "ivan.petrov@innovateai.ru",
        "+7",
        "495-555-7890",
        "DD-MM-YYYY",
        "HH:mm:ss",
        "Europe/Moscow",
      ],
    ],
  };
}

export function getNoticeSampleData() {
  return {
    SampleHeaders: [
      "Content",
      "Type",
      "Start Date",
      "Start Time",
      "End Date",
      "End Time",
      "Status",
      "Is Activated",
    ],
    SampleContent: [
      [
        "System maintenance from 12:00 AM to 3:00 AM.",
        "info",
        "2025-04-09",
        "00:00",
        "2025-04-09",
        "03:00",
        "Active",
        true,
      ],
      [
        "New features successfully deployed.",
        "success",
        "2025-03-31",
        "08:00",
        "2025-04-06",
        "18:00",
        "Active",
        true,
      ],
      [
        "Security alert: Beware of phishing.",
        "danger",
        "2025-04-02",
        "12:00",
        "2025-04-08",
        "23:59",
        "Active",
        true,
      ],
      [
        "Office closed on Friday (public holiday).",
        "info",
        "2025-04-10",
        "00:00",
        "2025-04-10",
        "23:59",
        "Inactive",
        false,
      ],
      [
        "Reception area renovation next week.",
        "info",
        "2025-04-14",
        "09:00",
        "2025-04-18",
        "17:00",
        "Inactive",
        false,
      ],
    ]
  };
}



export function getBadgeSampleData() {
  return {
    SampleHeaders: [
      "Badge Icon",
      "Badge Name",
      "Badge Type",
      "Description",
      "Achievement Criteria",
      "Status",
    ],
    SampleContent: [
      [
        "https://cdn-icons-png.flaticon.com/512/1828/1828884.png",
        "Super Achiever",
        "Achievement",
        "Awarded for outstanding performance.",
        "Complete 10 major tasks.",
        "Active",
      ],
      [
        "https://cdn-icons-png.flaticon.com/512/2583/2583333.png",
        "Early Bird",
        "Reward",
        "Given to users who log in before 6 AM.",
        "Log in before 6 AM for 7 consecutive days.",
        "Inactive",
      ],
      [
        "https://cdn-icons-png.flaticon.com/512/3515/3515383.png",
        "Milestone Master",
        "Milestone",
        "Earned after reaching a significant milestone.",
        "Reach level 50 in the system.",
        "Active",
      ],
      [
        "https://cdn-icons-png.flaticon.com/512/1998/1998694.png",
        "Consistent Performer",
        "Achievement",
        "Awarded for maintaining consistency.",
        "Complete at least one task per day for a month.",
        "Active",
      ],
      [
        "https://cdn-icons-png.flaticon.com/512/1077/1077035.png",
        "Helping Hand",
        "Reward",
        "Given to users who assist others frequently.",
        "Help 20 different users with their queries.",
        "Inactive",
      ],
    ],
  };
}

// export function getFaqSampleData() {
//   return {
//     SampleHeaders: [
//       "FAQ ID",
//       "Category",
//       "Question",
//       "Answer",
//       "Keywords",
//       "Status",
//       "Visibility",
//       "Featured",
//       "Tags",
//       "Priority",
//       "Updated By",
//     ],
//     SampleContent: [
//       [
//         "NET001",
//         "Technical",
//         "How can I reset my router?",
//         "To reset your router, press and hold the reset button for 10 seconds.",
//         ["Router", "Reset", "Internet"],
//         "Active",
//         "Public",
//         false,
//         ["Networking"],
//         // "Medium",
//         "Admin",
//       ],
//       [
//         "BILL202",
//         "Billing",
//         // "How can I check my billing history?",
//         "You can check your billing history in the 'My Account' section on our website.",
//         ["Billing", "Payment", "History"],
//         "Active",
//         "Public",
//         false,
//         ["Finance", "Account"],
//         "Medium",
//         "Admin",
//       ],
//       [
//         "PAY500",
//         "Payments",
//         "What payment methods do you accept?",
//         "We accept credit cards, debit cards, and PayPal.",
//         ["Payment", "Methods", "Options"],
//         "Active",
//         "Public",
//         true,
//         ["Transactions", "Checkout"],
//         "High",
//         "Admin",
//       ],
//       [
//         "SUP101",
//         "Support",
//         "How do I contact customer support?",
//         "You can reach customer support via email, phone, or live chat.",
//         ["Support", "Help", "Contact"],
//         "Active",
//         "Public",
//         true,
//         ["Customer Service"],
//         "High",
//         "Admin",
//       ],
//       [
//         "ACC789",
//         "Account",
//         "How do I change my account password?",
//         "Go to 'Settings' > 'Change Password' and follow the instructions.",
//         ["Account", "Password", "Security"],
//         "Active",
//         "Public",
//         false,
//         ["Security", "Login"],
//         "Medium",
//         "Admin",
//       ],
//       [
//         "SPEED333",
//         "Technical",
//         "How can I improve my internet speed?",
//         "Try restarting your router, closing unused applications, or upgrading your plan.",
//         ["Internet", "Speed", "Slow Connection"],
//         "Active",
//         "Public",
//         true,
//         ["Optimization", "Tech Help"],
//         "High",
//         "Admin",
//       ],
//       [
//         "UPGRADE101",
//         "General",
//         "Can I upgrade my broadband plan?",
//         "Yes, you can upgrade your plan anytime from the 'My Account' section.",
//         ["Upgrade", "Plan", "Broadband"],
//         "Active",
//         "Public",
//         true,
//         ["Subscriptions"],
//         "High",
//         "Admin",
//       ],
//       [
//         "OUTAGE999",
//         "Technical",
//         "What should I do during an internet outage?",
//         "Check for any service updates on our website or restart your router.",
//         ["Internet", "Outage", "Downtime"],
//         "Active",
//         "Public",
//         false,
//         ["Connectivity", "Troubleshooting"],
//         "Medium",
//         "Admin",
//       ],
//       [
//         "DISCOUNT777",
//         "Billing",
//         "Are there any ongoing discounts for new users?",
//         "Yes, we offer a 10% discount for new customers on their first bill.",
//         ["Discount", "New Users", "Promo"],
//         "Active",
//         "Public",
//         true,
//         ["Offers", "Savings"],
//         "Medium",
//         "Admin",
//       ],
//       [
//         "DEVICE456",
//         "Technical",
//         "Can I use my own modem instead of the one provided?",
//         "Yes, but it must be compatible with our network. Check our website for supported models.",
//         ["Modem", "Compatibility", "Device"],
//         "Active",
//         "Public",
//         false,
//         ["Hardware"],
//         "Medium",
//         "Admin",
//       ],
//     ],
//   };
// }
export function getFaqSampleData() {
  return {
    SampleHeaders: [
      "FAQ ID",
      "Category",
      "Question",
      "Answer",
      "Keywords",
      "Status",
      "Visibility",
      "Featured",
      "Tags",
      "Priority",
      "Updated By",
    ],
    SampleContent: [
      [
        "FTH201",
        "General",
        "What is the installation process for broadband?",
        "Installation is completed within 24-48 hours after payment confirmation.",
        ["Broadband", "Installation"],
        "Active",
        "Public",
        true,
        ["New connection"],
        "High",
        "Admin",
      ],
      [
        "FTH502",
        "Support",
        "How can I contact customer support?",
        "You can reach us via email, phone, or live chat on our website.",
        ["Support", "Help"],
        "Active",
        "Public",
        false,
        ["Customer Service"],
        "Medium",
        "Admin",
      ],
      [
        "NET404",
        "Network",
        "Why is my internet speed slow?",
        "Your speed may be affected by multiple connected devices or network congestion.",
        ["Network", "Slow Internet"],
        "Active",
        "Public",
        true,
        ["Troubleshooting"],
        "High",
        "Admin",
      ],
      [
        "FTH150",
        "Billing",
        "Are there any hidden charges in the bill?",
        "No, we maintain complete transparency with our billing process.",
        ["Billing", "Hidden Charges"],
        "Active",
        "Public",
        false,
        ["Billing Clarity"],
        "Low",
        "Admin",
      ],
      [
        "FTH250",
        "General",
        "Can I use my own router?",
        "Yes, you can use your own router as long as it's compatible with our network.",
        ["Router", "Compatibility"],
        "Active",
        "Public",
        true,
        ["Hardware"],
        "Medium",
        "Admin",
      ],
      [
        "PAY702",
        "Payments",
        "How do I enable auto-pay for my bills?",
        "You can enable auto-pay through the billing section in your account settings.",
        ["Auto-pay", "Billing"],
        "Active",
        "Public",
        true,
        ["Payments"],
        "Medium",
        "Admin",
      ],
      [
        "SEC401",
        "Security",
        "How do I secure my WiFi connection?",
        "Change your default WiFi password and enable WPA2 encryption.",
        ["Security", "WiFi"],
        "Active",
        "Public",
        true,
        ["Safety"],
        "High",
        "Admin",
      ],
      [
        "FTH888",
        "Plans",
        "What is the validity of my broadband plan?",
        "Most plans are valid for 30 days unless stated otherwise.",
        ["Plan", "Validity"],
        "Active",
        "Public",
        true,
        ["Subscription"],
        "Medium",
        "Admin",
      ],
      [
        "FTH901",
        "General",
        "Do you provide a free trial for new users?",
        "Yes, we offer a 7-day free trial for first-time users.",
        ["Trial", "New Customers"],
        "Active",
        "Public",
        true,
        ["Promotions"],
        "High",
        "Admin",
      ],
      [
        "BILL999",
        "Billing",
        "Can I get a refund if I cancel my plan early?",
        "Refund policies vary. Please check our terms and conditions.",
        ["Refund", "Billing"],
        "Active",
        "Public",
        false,
        ["Cancellation"],
        "Low",
        "Admin",
      ],
      [
        "SEC303",
        "Security",
        "How can I detect unauthorized users on my network?",
        "Check your router settings for a list of connected devices.",
        ["Security", "Unauthorized Access"],
        "Active",
        "Public",
        true,
        ["WiFi Security"],
        "Medium",
        "Admin",
      ],
      [
        "NET202",
        "Network",
        "Can I pause my internet service temporarily?",
        "Yes, you can request a temporary suspension through customer service.",
        ["Pause Service", "Network"],
        "Active",
        "Public",
        false,
        ["Service Hold"],
        "Medium",
        "Admin",
      ],
    ],
  };
}
