export const StaticResponseData = {
  aws: { GET: false, POST: false, PUT: false, DELETE: false },
  brand: { GET: false, POST: false, PUT: false, DELETE: false },
  companies: { GET: false, POST: false, PUT: false, DELETE: false },
  coupons: { GET: false, POST: false, PUT: false, DELETE: false },
  emailTemplates: { GET: false, POST: false, PUT: false, DELETE: false },
  dashboard: { GET: false, POST: false, PUT: false, DELETE: false },
  documentation: { GET: false, POST: false, PUT: false, DELETE: false },
  logs: { GET: false, POST: false, PUT: false, DELETE: false },
  notices: { GET: false, POST: false, PUT: false, DELETE: false },
  paymentRecord: { GET: false, POST: false, PUT: false, DELETE: false },
  paymentSetting: { GET: false, POST: false, PUT: false, DELETE: false },
  plans: { GET: false, POST: false, PUT: false, DELETE: false },
  roles: { GET: false, POST: false, PUT: false, DELETE: false },
  settings: { GET: false, POST: false, PUT: false, DELETE: false },
  smtp: { GET: false, POST: false, PUT: false, DELETE: false },
  user: { GET: false, POST: false, PUT: false, DELETE: false },
  mailerMagix: { GET: false, POST: false, PUT: false, DELETE: false },
  versionControl: { GET: false, POST: false, PUT: false, DELETE: false },
  responseMessage: { GET: false, POST: false, PUT: false, DELETE: false },
};

export const Staticdata = [
  { key: "dashboard", title: "Dashboard", pathname: "/dashboard" },
  { key: "companies", title: "Companies", pathname: "/companies" },
  { key: "plans", title: "Plans", pathname: "/plans" },
  { key: "user", title: "Admin Users", pathname: "/admin-users" },
  { key: "notices", title: "Notices", pathname: "/notices" },
  { key: "documentation", title: "Documentation", pathname: "/documentation" },
  {
    key: "paymentRecord",
    title: "Payment",
    pathname: "/payment-record",
  },
  { key: "coupons", title: "Coupons", pathname: "/coupons" },

  { key: "logs", title: "Logs", pathname: "/logs" },
  { key: "responseMessage", title: "Response Message", pathname: "/response-messages" },
  { key: "brand", title: "Brand", pathname: "/brand" },
  { key: "smtp", title: "SMTP Settings", pathname: "/smtp" },
  {
    key: "paymentSetting",
    title: "Payment Setting",
    pathname: "/payment-setting",
  },
  { key: "settings", title: "Global Settings", pathname: "/settings" },
  { key: "aws", title: "AWS Settings", pathname: "/aws" },
  { key: "roles", title: "Role Management", pathname: "/roles" },
  { key: "mailerMagix", title: "Mailer Magix", pathname: "/mailer-magix" },
  { key: "versionControl", title: "Extension Version Control", pathname: "/version-control" },
  {
    key: "emailTemplates",
    title: "Email Template",
    pathname: "/email-template",
  },

];



export const baseUsersData = [
  {
    id: "0",
    permissionRender: "dashboard",
    permission: "Dashboard",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "1",
    permissionRender: "companies",
    permission: "Companies",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "2",
    permissionRender: "plans",
    permission: "Plans",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "3",
    permissionRender: "user",
    permission: "Admin Users",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "4",
    permissionRender: "notices",
    permission: "Notices",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "5",
    permissionRender: "documentation",
    permission: "Documentation",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "6",
    permissionRender: "paymentRecord",
    permission: "Payment",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "7",
    permissionRender: "coupons",
    permission: "Coupons",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "8",
    permissionRender: "logs",
    permission: "Logs",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "9",
    permissionRender: "responseMessage",
    permission: "Response Message",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "10",
    permissionRender: "brand",
    permission: "Brand",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "11",
    permissionRender: "smtp",
    permission: "SMTP Settings",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "12",
    permissionRender: "paymentSetting",
    permission: "Payment Setting",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "13",
    permissionRender: "settings",
    permission: "Global Settings",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "14",
    permissionRender: "aws",
    permission: "AWS Settings",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "15",
    permissionRender: "roles",
    permission: "Role Management",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "16",
    permissionRender: "mailerMagix",
    permission: "Mailer Magix",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "17",
    permissionRender: "versionControl",
    permission: "Extension Version Control",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
  {
    id: "18",
    permissionRender: "emailTemplates",
    permission: "Email Template",
    GET: true,
    POST: false,
    PUT: false,
    DELETE: false,
  },
];